import { useState, type ReactNode } from 'react';
import { Link } from 'wouter';
import { Home, LogOut, Menu, Target } from 'lucide-react';
import { Brand } from '@/components/brand';

export function AppShell({ children, active, user, onSignOut }: { children: ReactNode; active: string; user: string; onSignOut: () => void }) {
  const [open, setOpen] = useState(false);
  const links = [{ href: '/dashboard', label: 'Overview', icon: Home }, { href: '/progress', label: 'My progress', icon: Target }];
  return <div className="grain min-h-[100dvh] bg-background"><aside className={`fixed inset-y-0 left-0 z-40 flex w-[265px] flex-col border-r border-border bg-[#f4f3e9] p-6 transition-transform duration-300 lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><Brand /><div className="mt-14"><span className="font-mono-ui px-3 text-[10px] uppercase tracking-[.2em] text-muted-foreground">Your space</span><nav className="mt-4 space-y-1">{links.map(({ href, label, icon: Icon }) => <Link key={href} href={href} data-testid={`link-nav-${label.toLowerCase().replace(' ', '-')}`} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition ${active === href ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><Icon size={17} />{label}</Link>)}</nav></div><div className="mt-auto rounded-2xl bg-[#e4efe7] p-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#f1c98b] text-xs font-bold text-[#173f38]">{user.slice(0, 2).toUpperCase()}</span><div><p className="text-sm font-bold">{user}</p><p className="text-[11px] text-muted-foreground">Beginner path</p></div></div><button data-testid="button-sign-out" onClick={onSignOut} className="mt-4 flex items-center gap-2 text-xs font-semibold text-muted-foreground hover:text-destructive"><LogOut size={14} /> Sign out</button></div></aside>{open && <button aria-label="Close menu" data-testid="button-close-menu" onClick={() => setOpen(false)} className="fixed inset-0 z-30 bg-[#173f38]/20 lg:hidden" />}<div className="lg:pl-[265px]"><header className="flex items-center justify-between border-b border-border bg-background/90 px-5 py-4 backdrop-blur md:px-10"><button data-testid="button-open-menu" onClick={() => setOpen(true)} className="rounded-lg p-2 hover:bg-muted lg:hidden"><Menu size={20} /></button><div className="hidden text-sm text-muted-foreground lg:block">A little practice goes a long way.</div><div className="ml-auto flex items-center gap-3"><span className="hidden text-right sm:block"><span className="block text-xs font-bold">{user}</span><span className="block text-[11px] text-muted-foreground">Learning ISL</span></span><span className="grid h-9 w-9 place-items-center rounded-full bg-primary text-xs font-bold text-primary-foreground">{user.slice(0, 2).toUpperCase()}</span></div></header><main className="mx-auto max-w-7xl px-5 py-8 md:px-10 md:py-12">{children}</main></div></div>;
}
